server:
  port: 9002
  servlet:
    context-path: /novel


spring:
  application:
    name: novel-web
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.215:3306/vnovel?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=Hongkong&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    port: 6379
    host: 192.168.1.215
    database: 5
    password: dgbigdata123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true

#------------------- 自定义属性--------------------------
novel:
  # JWT密钥
  jwt:
    secret: E66559580A1ADF48CDD928516062F12E















